# coding: utf-8

import inherited_base_partner_merge
import inherited_partner
import inherited_partner_contact_identification_assignation
import inherited_tpa_config_settings
import inherited_tpa_synchronization_merge
import inherited_tpa_synchronization_status
import inherited_user
